Null safety migration
vanlooverenkoen/moor_db_viewer pull request #29
Opened 2021-03-05 11:34 UTC by justacid

Hi there, thanks for the package!

This PR adds support for null-safety (see #28).
I have tested the example app on Android and iOS 
and everything seems to be working fine.

Cheers

2021-03-05 11:35 UTC, vanlooverenkoen commented
Very nice! I tought I migrated all my packages yesterday. but indeed the db viewer for moor is something I forgot. I will do the review right away

2021-03-05 11:47 UTC, vanlooverenkoen requested changes
Thanks for your contribution. I will probably have to test it myself. I have some time this weekend to do the testing as well.

2021-03-05 11:47 UTC, vanlooverenkoen commented on lib/src/screen/moor_table_content_list_screen.dart
> +    if (_key.currentContext != null) {
move this to a seperate local variable. So you don't have to do the null check twice

2021-03-05 11:47 UTC, vanlooverenkoen commented on lib/src/screen/moor_table_filter_screen.dart
> +    if (result != null && _scaffoldKey.currentContext != null) {
move context to a seperate variable

2021-03-05 11:47 UTC, vanlooverenkoen commented on lib/src/screen/moor_table_filter_screen.dart
> +    if (result != null && _scaffoldKey.currentContext != null) {
move context to a seperate variable

2021-03-05 11:47 UTC, vanlooverenkoen commented on lib/src/widget/filter/where/where_string_widget.dart
> +    if (value != null) {
if (value == null) return

2021-03-05 11:47 UTC, vanlooverenkoen commented on lib/src/widget/filter/where/where_int_widget.dart
> +    if (value != null) {
if (value == null) return

2021-03-05 11:47 UTC, vanlooverenkoen commented on lib/src/widget/filter/where/where_double_widget.dart
> +    if (value != null) {
if (value == null) return

2021-03-05 14:00 UTC, justacid commented
Thanks for taking the time! I have addressed your review comments. :)

2021-03-05 14:01 UTC, vanlooverenkoen commented
Alright looks good. I will do the extra testing this weekend. Thanks again for your contribution

2021-03-06 09:58 UTC, vanlooverenkoen approved these changes

2021-03-06 09:58 UTC, merged

2021-03-06 10:04 UTC, vanlooverenkoen commented
released in 3.0.0